### ISSUE TITLE
Fatal error during generation

### ISSUE THREAD

**Issue by mieszkomalawski** [unigen/unigen#2]
PHP Fatal error:  Uncaught Error: Call to undefined method ReflectionType::getName() in /data/application/vendor/unigen/unigen/src/Sut/Adapter/ReflectionSutDependencyAdapter.php:60
Stack trace:
#0 /data/application/vendor/twig/twig/lib/Twig/Extension/Core.php(1619): UniGen\Sut\Adapter\ReflectionSutDependencyAdapter->getType()
#1 /data/application/vendor/twig/twig/lib/Twig/Environment.php(378) : eval()'d code(45): twig_get_attribute(Object(Twig_Environment), Object(Twig_Source), Object(UniGen\Sut\Adapter\ReflectionSutDependencyAdapter), 'getType', Array)
#2 /data/application/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_b739c7b64413a4a76f246fb51d56f7a39d34da7375fe7a73e5929d96de8c97e7->doDisplay(Array, Array)
#3 /data/application/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Template->displayWithErrorHandling(Array, Array)
#4 /data/application/vendor/twig/twig/lib/Twig/Template.php(375): Twig_Template->display(Array)
#5 /data/application/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Arra in /data/application/vendor/unigen/unigen/src/Sut/Adapter/ReflectionSutDependencyAdapter.php on line 60

**Comment by KamilKujawa** [comment]
Fixed in #3
